<a href="https://colab.research.google.com/github/Arkrishx/python-data-analytics-/blob/main/Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Error handling

In [ ]:
#error hanling

try:
  n = int(input("Enter a number:"))
  print(n)

except:
  print("Invalid input")

Enter a number:ak
Invalid input


In [ ]:
#practice: Attendence Calculator

def percentage(x,y):
  perc = (y/x)*100
  return round(perc,2 )

def status(percentage):
  if percentage >= 75:
    return "Eligible"
  else:
    return "Not eligible"

try:
  x = int(input("Total classes:"))
  y = int(input("classes attented:"))

  pct = percentage(x,y)
  st = status(pct)

  print("Percentage:",pct,"%")
  print("Status:",st)

except:
  print("Invalid input")

Total classes:11
classes attented:6
Percentage: 54.55 %
Status: Not eligible


# Numpy

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5]) #1D arr
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr = np.array([[1,2],[2,4]]) #2D arr
print(arr)

[[1 2]
 [2 4]]


In [ ]:
import numpy as np
arr = np.array([[[1,2],[2,4]],[[3,5],[6,7]]]) #3D arr
print(arr)

[[[1 2]
  [2 4]]

 [[3 5]
  [6 7]]]


# Numpy array function

In [3]:
# zeros()

import numpy as np
arr = np.zeros([2,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# ones()

import numpy as np
arr = np.ones([2,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#arange()

import numpy as np
arr = np.arange(1,10)
print(arr)


arr2 = np.arange(1,10,2)
print(arr2)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [10]:
# linspace() --> evenly spaced value

import numpy as np
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [14]:
#random.rand()

import numpy as np
arr = np.random.rand(3)
res = np.round(arr,2)
print(res)


[0.25 0.67 0.89]


In [15]:
#eye()  --> Identity Matrix

import numpy as np
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Array operation

In [16]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

#addition
c = a+b
print(c)

#multiplication
d= a*b
print(d)

#power
e = a**2
print(e)

#sqrt
f = np.sqrt(a)
print(f)

#sum
g = np.sum(a)
print(g)

[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]
6
